# Generated by Django 4.1.7 on 2023-03-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير الموقع'), ('install_supervisor', ' مدير التركيبات'), ('repair_supervisor', '  مدير الصيانة'), ('quarter_supervisor', 'مشرف كوارتر '), ('company', 'شركة'), ('sales', 'بائع'), ('accountant', 'محاسب'), ('technician', 'فني'), ('excution', 'تنفيذ كوارتر '), ('quarter_sales', 'مبيعات كوارتر '), ('egypt_office', 'مكتب مصر  ')], default='sales', max_length=25),
        ),
    ]
