# Generated by Django 4.1.7 on 2023-03-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_created_by_customer_cretaed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cretaed_at',
            new_name='created_at',
        ),
    ]
