# Generated by Django 4.1.7 on 2023-03-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cretaed_at_customer_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=3)),
            ],
        ),
    ]
