# Generated by Django 4.1.7 on 2023-03-21 07:55

from django.db import migrations



def create_latedays(apps, schema_editor):
    LateDays = apps.get_model('core', 'LateDays')
    LateDays.objects.create(days=3)



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_latedays'),
    ]

    operations = [
        migrations.RunPython(create_latedays),
    ]
