# Generated by Django 4.1.7 on 2023-03-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230321_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latedays',
            options={'verbose_name_plural': 'Late Days'},
        ),
    ]
