# Generated by Django 3.1.7 on 2021-03-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210322_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'supervisor'), (3, 'technician')], default=1, verbose_name='الوظيفة'),
        ),
    ]
