# Generated by Django 3.1.7 on 2021-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210412_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='submitted_orders',
            field=models.IntegerField(default=0),
        ),
    ]
