# Generated by Django 3.1.7 on 2021-04-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210418_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='${user}',
            field=models.ImageField(blank=True, null=True, upload_to='user_data/profile_pics'),
        ),
        migrations.AddField(
            model_name='user',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='user_data/files'),
        ),
    ]
