# Generated by Django 3.1.7 on 2021-04-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210421_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='${user}',
            new_name='profile_pic',
        ),
    ]
