# Generated by Django 3.1.7 on 2021-08-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210519_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='install',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quarter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='repair',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مدير الموقع'), (2, 'مدير التركيبات'), (3, 'مدير الصيانة'), (4, 'مشرف كوارتر '), (5, 'مندوب بيع '), (6, 'حسابات'), (7, 'مكتب مصر '), (8, 'فني '), (9, 'تنفيذ كوارتر')], default=1, verbose_name='الوظيفة'),
        ),
    ]
