# Generated by Django 3.1.7 on 2022-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210813_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'مدير الموقع'), (2, 'مدير التركيبات'), (3, 'مدير الصيانة'), (4, 'مشرف كوارتر '), (5, 'مندوب بيع '), (6, 'حسابات'), (7, 'مكتب مصر '), (8, 'فني '), (9, 'تنفيذ كوارتر'), (10, 'مبيعات كوارتر'), (11, 'شركة')], default=1, verbose_name='الوظيفة'),
        ),
    ]
