# Generated by Django 3.1.7 on 2021-03-28 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default=1, max_length=10)),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
                ('machine_type', models.CharField(max_length=200)),
                ('customer_type', models.CharField(choices=[('cash', 'كاش'), ('warranty', 'ضمان')], max_length=10)),
                ('invoice_number', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('new', 'جديد'), ('under_process', 'قيد التنفيذ'), ('suspended', 'معلق'), ('done', 'تم'), ('closed', 'انتهي')], default='new', max_length=25)),
                ('file', models.FileField(blank=True, null=True, upload_to='repair/files/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=20)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service_request')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
