# Generated by Django 4.1.7 on 2023-03-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='cretaed_at',
            new_name='created_at',
        ),
    ]
