# Generated by Django 4.1.7 on 2023-03-18 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_created_by_alter_service_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='service',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
            preserve_default=False,
        ),
    ]
