# Generated by Django 3.1.7 on 2021-04-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210328_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_appointment', to='service.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='service.service_request'),
        ),
    ]
