# Generated by Django 3.1.7 on 2021-04-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210421_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_request',
            name='service_type',
            field=models.CharField(choices=[('repair', 'صيانة'), ('install', 'تركيب')], max_length=10),
        ),
    ]
