# Generated by Django 3.1.7 on 2021-04-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210423_2058'),
        ('service', '0005_auto_20210421_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
    ]
