# Generated by Django 4.1.7 on 2023-03-18 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0005_holdreason_holdfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdreason',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holdreason',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hold_canceled_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
