# Generated by Django 3.1.7 on 2021-04-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_request_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='request_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
