# Generated by Django 3.1.7 on 2021-04-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_service_request_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_request',
            name='request_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
