# Generated by Django 3.1.7 on 2021-05-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20210506_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_request',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('under_process', 'قيد التنفيذ'), ('done', 'تم'), ('closed', 'انتهي')], default='new', max_length=25),
        ),
    ]
