# Generated by Django 4.1.7 on 2023-03-21 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0009_service_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_by']},
        ),
        migrations.CreateModel(
            name='SparePartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_parts', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('pending', 'مطلوب'), ('recieved', 'تم الاستلام')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'verbose_name': 'Spare Part Reauest',
                'verbose_name_plural': 'Spare Part Reauests',
            },
        ),
    ]
