# Generated by Django 3.1.7 on 2021-05-16 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0010_auto_20210509_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_request',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_appointment', to='service.appointment'),
        ),
        migrations.AlterField(
            model_name='service_request',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='service/files/'),
        ),
        migrations.CreateModel(
            name='Hold_reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='hold_files/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('hold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_on_hold', to='service.service_request')),
            ],
        ),
        migrations.AddField(
            model_name='service_request',
            name='hold_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.hold_reason'),
        ),
    ]
