# Generated by Django 3.1.7 on 2021-05-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20210516_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
