# Generated by Django 4.1.7 on 2023-03-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_service_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
