# Generated by Django 3.1.7 on 2021-05-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20210517_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('repair', 'صيانة'), ('install', 'تركيب')], default='test', max_length=100),
            preserve_default=False,
        ),
    ]
