# Generated by Django 4.1.7 on 2023-03-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_sparepartrequest_recievied_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AddField(
            model_name='holdreason',
            name='details',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('under_process', 'قيد التنفيذ'), ('done', 'تم'), ('closed', 'انتهي')], default='new', max_length=15),
        ),
    ]
