# Generated by Django 3.1.7 on 2021-09-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_latedays'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
