# Generated by Django 4.1.7 on 2023-04-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_service_options_holdreason_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ac_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
