# Generated by Django 4.1.7 on 2023-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_service_ac_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ac_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
