# Generated by Django 3.1.7 on 2021-09-26 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_service_request_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcutionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service/files/excution_files')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service_request')),
            ],
        ),
        migrations.AddField(
            model_name='service_request',
            name='excution_files',
            field=models.ManyToManyField(blank=True, related_name='service_files', to='service.ExcutionFile'),
        ),
    ]
