# Generated by Django 4.1.7 on 2023-04-04 19:55

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_service_ac_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=service.models.get_file_path),
        ),
    ]
