# Generated by Django 3.1.7 on 2022-02-07 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0017_auto_20210926_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
