# Generated by Django 4.1.7 on 2024-09-28 09:55

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excutionfile',
            name='file',
            field=models.FileField(upload_to=service.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='holdfile',
            name='file',
            field=models.FileField(upload_to=service.models.get_file_path),
        ),
    ]
