# Generated by Django 3.1.7 on 2022-02-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_service_request_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service/files/request_files')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service_request')),
            ],
        ),
        migrations.AddField(
            model_name='service_request',
            name='request_files',
            field=models.ManyToManyField(blank=True, null=True, related_name='request_files', to='service.RequestFile'),
        ),
    ]
