# Generated by Django 3.1.7 on 2022-02-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repair', '0010_auto_20220214_1326'),
        ('service', '0019_auto_20220211_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='spare_part_request',
            field=models.ManyToManyField(blank=True, related_name='spare_parts', to='repair.SparePartRequst'),
        ),
    ]
