# Generated by Django 4.1.7 on 2023-03-30 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quarter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(default=quarter.models.generate_ref_number, max_length=12, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('new', 'جديد'), ('negotiation', 'مفاوضات'), ('waiting_designes', 'انتظار التصاميم و العقود'), ('waiting_approval', 'انتظار توقيع العقد'), ('under_process', 'جاري التنفيذ'), ('done', 'تم التنفيذ'), ('canceled', 'ملغي')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
