# Generated by Django 3.1.7 on 2021-06-11 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210423_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='designes/')),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(1, 'approved'), (2, 'pending'), (3, 'rejected')], default='pending', max_length=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Excution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=10)),
                ('files', models.FileField(upload_to='pricing/')),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(1, 'approved'), (2, 'pending'), (3, 'rejected')], default='pending', max_length=15)),
                ('rejection_notes', models.TextField(blank=True, max_length=500)),
                ('proposed_price', models.CharField(blank=True, max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='purchase/')),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('cost', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quarter_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='اسم العميل ')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='البريد الاليكتروني')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='ملاحظات / بيانات اضافية ')),
                ('status', models.IntegerField(choices=[(1, 'جديد'), (2, 'قيد التسعير'), (3, 'مراجعة التسعير'), (4, 'التفاوض'), (5, 'انتظار التحويل المالي الأول'), (6, 'مراجعة التحويل المالي'), (7, 'التصميم'), (8, 'مراجعة التصاميم '), (9, ' التنفيذ الأول'), (10, 'التحويل الثاني '), (11, 'مراجعة التحويل الثاني '), (12, 'التنفيذ الثاني '), (13, 'تمت '), (14, 'المشتريات')], default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('hold', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='service/files/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('designs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quarter.design')),
                ('first_excution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first', to='quarter.excution')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('transfer1_qty', models.IntegerField(default=0)),
                ('transfer1_date', models.DateTimeField(blank=True, null=True)),
                ('transfer1_file', models.FileField(blank=True, null=True, upload_to='transfer/')),
                ('transfer1_notes', models.TextField(blank=True, max_length=500)),
                ('transfer2_qty', models.IntegerField(default=0)),
                ('transfer2_date', models.DateTimeField(blank=True, null=True)),
                ('transfer2_file', models.FileField(blank=True, null=True, upload_to='transfer/')),
                ('transfer2_notes', models.TextField(blank=True, max_length=500)),
                ('transfer3_qty', models.IntegerField(default=0)),
                ('transfer3_date', models.DateTimeField(blank=True, null=True)),
                ('transfer3_file', models.FileField(blank=True, null=True, upload_to='transfer/')),
                ('transfer3_notes', models.TextField(blank=True, max_length=500)),
                ('outstanding_ammount', models.IntegerField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarter.quarter_service')),
            ],
        ),
        migrations.AddField(
            model_name='quarter_service',
            name='money_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quarter.transfer'),
        ),
        migrations.AddField(
            model_name='quarter_service',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quarter.price'),
        ),
        migrations.AddField(
            model_name='quarter_service',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quarter.purchase'),
        ),
        migrations.AddField(
            model_name='quarter_service',
            name='second_excution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='quarter.excution'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarter_service', to='quarter.quarter_service'),
        ),
        migrations.AddField(
            model_name='price',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarter.quarter_service'),
        ),
        migrations.CreateModel(
            name='ExcutionFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='excution/')),
                ('excution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_service', to='quarter.excution')),
            ],
        ),
        migrations.AddField(
            model_name='excution',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='docs', to='quarter.ExcutionFiles'),
        ),
        migrations.AddField(
            model_name='excution',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarter.quarter_service'),
        ),
        migrations.AddField(
            model_name='design',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarter.quarter_service'),
        ),
    ]
