# Generated by Django 3.1.7 on 2021-06-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter_service',
            name='status',
            field=models.IntegerField(choices=[(1, 'جديد'), (2, 'قيد التسعير'), (3, 'مراجعة التسعير'), (4, 'التفاوض'), (5, 'انتظار التحويل المالي الأول'), (6, 'مراجعة التحويل المالي'), (7, 'التصميم'), (8, 'مراجعة التصاميم '), (9, ' التنفيذ الأول'), (10, 'التحويل الثاني '), (11, 'مراجعة التحويل الثاني '), (12, 'التنفيذ الثاني '), (13, 'انتهاء التنفيذ'), (15, 'تمت '), (14, 'المشتريات')], default=1),
        ),
    ]
