# Generated by Django 4.1.7 on 2023-03-31 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quarter', '0002_negotiation'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quarter/files')),
            ],
        ),
        migrations.AlterField(
            model_name='quarterproject',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('negotiation', 'مفاوضات'), ('waiting_designs', 'انتظار التصاميم و العقود'), ('waiting_approval', 'انتظار توقيع العقد'), ('under_process', 'جاري التنفيذ'), ('done', 'تم التنفيذ'), ('canceled', 'ملغي')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(to='quarter.file')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarter.quarterproject')),
            ],
        ),
    ]
