# Generated by Django 3.1.7 on 2021-04-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0002_auto_20210414_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter_service',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quarter.status'),
        ),
    ]
