# Generated by Django 4.1.7 on 2023-04-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0003_file_alter_quarterproject_status_projectfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfiles',
            options={'verbose_name_plural': 'Project Files'},
        ),
        migrations.AlterModelOptions(
            name='quarterproject',
            options={'ordering': ['-created_at']},
        ),
    ]
