# Generated by Django 4.1.7 on 2023-04-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0004_alter_projectfiles_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterproject',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
