# Generated by Django 3.1.7 on 2021-04-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0004_quarter_service_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarter_service',
            name='current_status',
        ),
        migrations.AddField(
            model_name='quarter_service',
            name='status',
            field=models.CharField(default='new', max_length=10),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
