# Generated by Django 4.1.7 on 2023-04-04 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quarter', '0005_quarterproject_closed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterproject',
            name='rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_rep', to=settings.AUTH_USER_MODEL),
        ),
    ]
