# Generated by Django 4.1.7 on 2024-09-28 09:55

from django.db import migrations, models
import quarter.models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0006_quarterproject_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=quarter.models.get_file_path),
        ),
    ]
