# Generated by Django 3.1.7 on 2021-04-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0006_auto_20210415_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='files',
            field=models.FileField(upload_to='pricing/'),
        ),
    ]
