# Generated by Django 3.1.7 on 2021-04-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0007_auto_20210415_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('transfer1_qty', models.IntegerField(default=0)),
                ('transfer1_date', models.DateTimeField(blank=True)),
                ('transfer1_file', models.FileField(blank=True, null=True, upload_to='transfer/')),
                ('transfer1_notes', models.TextField(blank=True, max_length=500)),
                ('transfer2_qty', models.IntegerField(default=0)),
                ('transfer2_date', models.DateTimeField(blank=True)),
                ('transfer2_file', models.FileField(blank=True, null=True, upload_to='transfer/')),
                ('transfer2_notes', models.TextField(blank=True, max_length=500)),
                ('transfer3_qty', models.IntegerField(default=0)),
                ('transfer3_date', models.DateTimeField(blank=True)),
                ('transfer3_file', models.FileField(blank=True, null=True, upload_to='transfer/')),
                ('transfer3_notes', models.TextField(blank=True, max_length=500)),
                ('outstanding_ammount', models.IntegerField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarter.quarter_service')),
            ],
        ),
    ]
