# Generated by Django 3.1.7 on 2021-04-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0008_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer1_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer2_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer3_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
