# Generated by Django 3.1.7 on 2021-04-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0009_auto_20210415_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter_service',
            name='money_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quarter.transfer'),
        ),
    ]
