# Generated by Django 3.1.7 on 2021-04-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0010_quarter_service_money_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter_service',
            name='status',
            field=models.CharField(default='new', max_length=30),
        ),
        migrations.CreateModel(
            name='Designes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='designes/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarter.quarter_service')),
            ],
        ),
    ]
