# Generated by Django 3.1.7 on 2021-04-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0013_design_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter_service',
            name='status',
            field=models.CharField(choices=[(1, 'جديد'), (2, 'قيد التسعير'), (3, 'مراجعة التسعير'), (4, 'التفاوض'), (5, 'انتظار التحويل المالي الأول'), (6, 'مراجعة التحويل المالي'), (7, 'التصميم'), (8, 'مراجعة التصاميم '), (9, 'التنفيذ')], default=1, max_length=30),
        ),
    ]
