# Generated by Django 3.1.7 on 2021-04-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0014_auto_20210416_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter_service',
            name='status',
            field=models.IntegerField(choices=[(1, 'جديد'), (2, 'قيد التسعير'), (3, 'مراجعة التسعير'), (4, 'التفاوض'), (5, 'انتظار التحويل المالي الأول'), (6, 'مراجعة التحويل المالي'), (7, 'التصميم'), (8, 'مراجعة التصاميم '), (9, 'التنفيذ')], default=1),
        ),
    ]
