# Generated by Django 3.1.7 on 2021-04-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0017_quarter_service_cusomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarter_service',
            old_name='cusomer',
            new_name='customer',
        ),
    ]
