# Generated by Django 3.1.7 on 2021-04-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0018_auto_20210424_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter_service',
            name='request_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
