# Generated by Django 3.1.7 on 2021-05-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0019_quarter_service_request_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter_service',
            name='hold',
            field=models.BooleanField(default=True),
        ),
    ]
