# Generated by Django 3.1.7 on 2021-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0020_quarter_service_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter_service',
            name='hold',
            field=models.BooleanField(default=False),
        ),
    ]
