# Generated by Django 3.1.7 on 2021-05-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0021_auto_20210506_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='proposed_price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='price',
            name='rejection_notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='price',
            name='status',
            field=models.CharField(choices=[('approved', 1), ('pending', 2), ('rejected', 3)], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='quarter_service',
            name='status',
            field=models.IntegerField(choices=[(1, 'جديد'), (2, 'قيد التسعير'), (3, 'مراجعة التسعير'), (4, 'التفاوض'), (5, 'انتظار التحويل المالي الأول'), (6, 'مراجعة التحويل المالي'), (7, 'التصميم'), (8, 'مراجعة التصاميم '), (9, 'التنفيذ'), (10, 'التحويل الثاني '), (11, 'مراجعة التحويل الثاني '), (12, 'التنفيذ الثاني '), (13, 'تمت ')], default=1),
        ),
    ]
