# Generated by Django 3.1.7 on 2021-05-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0024_auto_20210518_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter_service',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='service/files/'),
        ),
        migrations.AlterField(
            model_name='quarter_service',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='البريد الاليكتروني'),
        ),
        migrations.AlterField(
            model_name='quarter_service',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='quarter_service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم العميل '),
        ),
        migrations.AlterField(
            model_name='quarter_service',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ملاحظات / بيانات اضافية '),
        ),
        migrations.AlterField(
            model_name='quarter_service',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='quarter_service',
            name='status',
            field=models.IntegerField(choices=[(1, 'جديد'), (2, 'قيد التسعير'), (3, 'مراجعة التسعير'), (4, 'التفاوض'), (5, 'انتظار التحويل المالي الأول'), (6, 'مراجعة التحويل المالي'), (7, 'التصميم'), (8, 'مراجعة التصاميم '), (9, ' التنفيذ الأول'), (10, 'التحويل الثاني '), (11, 'مراجعة التحويل الثاني '), (12, 'التنفيذ الثاني '), (13, 'تمت ')], default=1),
        ),
    ]
