# Generated by Django 3.1.7 on 2021-06-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarter', '0025_auto_20210531_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
